# Generated by Django 4.2.4 on 2023-08-02 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_hackathonregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='enrolled_users',
            field=models.ManyToManyField(related_name='enrolled_hackathons', through='api.HackathonRegistration',
                                         to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('user', 'hackathon')},
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
