# Generated by Django 4.2.4 on 2023-08-02 15:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_alter_hackathon_enrolled_users_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hackathonregistration',
            unique_together={('user', 'hackathon')},
        ),
    ]
